# spring:
#   #配置redis数据库
#   redis:
#     host: 192.168.21.162
#     port: 36379
#     password: MTS-redis2019
#     timeout: 6000ms       # 连接超时时间（毫秒）
#     jedis:
#         pool:
#         max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
#         max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#         max-idle: 10      # 连接池中的最大空闲连接
#         min-idle: 0       # 连接池中的最小空闲连接
spring:
  #配置redis数据库
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 6000       # 连接超时时间（毫秒）
    jedis:
        pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接

ctgCache:
  type: hosts
  url: 192.168.115.112:31078,192.168.115.113:31078
  instanceName: cxcache01
  password: FfcsCloud@2022
  pool:
    config:
      maxTotal: 10
      maxIdle: 10
      minIdle: 3
# ctgCache:
#   type: hosts
#   url: 127.0.0.1:3107,127.0.0.1:3108
#   instanceName: cxcache01
#   password: FfcsCloud@2022
#   pool:
#     config:
#       maxTotal: 10
#       maxIdle: 10
#       minIdle: 3
